site_name: Tabulator for Python

theme:
  name: material
  palette:
    primary: "green"
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Get started:
    - Welcome to Tabulator for Python: index.md
    - Detailed example: example.md
    - Changelog: changelog.md
  - Concepts:
      - Table: table.md
      - Columns and filters: columns.md
      - Events and triggers: events.md

repo_name: py-tabulator
repo_url: https://github.com/eodaGmbH/py-tabulator

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.snippets:
      check_paths: true
      base_path: [docs/examples, "."]
